default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cau_development
  username: <%= ENV['DATABASE_DEV_USERNAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>

test:
  <<: *default
  database: cau_test

production:
  <<: *default
  database: cau_production
  username: <%= ENV['DATABASE_PROD_USERNAME'] %>
  password: <%= ENV['DATABASE_PROD_PASSWORD'] %>
